name: Export Godot Game

on:
  push:
    branches: [ main, master ]

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game and create release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Godot Mono
        uses: firebelley/godot-export@v3.0.0
        with:
          # Using the STANDARD version instead of Mono to avoid extraction issues
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
